* Hausaufgaben Tag 1
Mach dir am besten für die Hausaufgaben einen neuen Order, damit man die Dateien dann schnell
wiederfinden kann.

** Sternmuster 1

In dieser Aufgabe geht es darum, verschiedene Muster auf dem Terminal auszugeben. Das erste ist ein
Dreieck. Der Benutzer wird zuerst nach einer natürlichen Zahl gefragt und dann soll ein Dreieck mit
der Größe der Eingabe des Benutzers ausgegeben werden.

Das sieht dann zum Beispiel so aus, wenn der Benutzer =7= eingibt:

#+begin_src
 Geben Sie eine Größe ein: 7

 *
 **
 ***
 ****
 *****
 ******
 *******
#+end_src

Oder so:


#+begin_src
 Geben Sie eine Größe ein: 3

 *
 **
 ***
#+end_src

** Sternmuster 2
Als nächstes wollen wir das Dreieck andersherum ausgeben:

#+begin_src
 Geben Sie eine Größe ein: 7

       *
      **
     ***
    ****
   *****
  ******
 *******
#+end_src

Oder auch:

#+begin_src
 Geben Sie eine Größe ein: 3

   *
  **
 ***
#+end_src

** Sternmuster 3
Jetzt kombinieren wir die Muster aus 1 und 2 und wollen dieses Muster erstellen:

#+begin_src
 Geben Sie eine Größe ein: 7

       * *
      ** **
     *** ***
    **** ****
   ***** *****
  ****** ******
 ******* *******
#+end_src

Oder auch:

#+begin_src
 Geben Sie eine Größe ein: 3

   * *
  ** **
 *** ***
#+end_src
** Summe aller Zahlen in einem Intervall
Schreibe ein Programm, dass den Benutzer nach einer natürlichen Zahl fragt und dann die Summe aller
Zahlen von 0 bis zu dieser Zahl berechnet. Das sieht dann zum Beispiel so aus:

#+begin_src
 Geben Sie eine Zahl ein: 4
 10
#+end_src

10 ist das Ergebnis weil:
$1+2+3+4=10$

Oder

#+begin_src
 Geben Sie eine Zahl ein: 10
 55
#+end_src
55 ist das Ergebnis weil:
$1+2+3+4+5+6+7+8+9+10=55$

** Summe aller geraden Zahlen in einem Intervall
Jetzt erweitern wir das Programm aus der letzten Aufgabe sodass nur noch die Summe der geraden
Zahlen berechnet wird:


#+begin_src
 Geben Sie eine Zahl ein: 4
 6
#+end_src

6 ist das Ergebnis weil:
$2+4=6$

Oder

#+begin_src
 Geben Sie eine Zahl ein: 10
 30
#+end_src
55 ist das Ergebnis weil:
$2+4+6+8+10=30$
** FizzBuzz
Schreibe ein Programm, das die Zahlen von 1 bis 100 ausgibt. Aber:
 - Wenn die Zahl durch 3 teilbar ist, gebe stattdessen "Fizz" aus.
 - Wenn die Zahl durch 5 teilbar ist, gebe "Buzz" aus.
 - Wenn sie durch 3 und 5 teilbar ist, gebe "FizzBuzz" aus.

Das sieht dann so aus:

#+begin_src
 1
 2
 Fizz
 4
 Buzz
 Fizz
 7
 8
 Fizz
 Buzz
 11
 Fizz
 13
 14
 FizzBuzz
 16
 ...
#+end_src
** Quadratzahlen
Schreibe ein Programmm, das den Benutzer immer wieder und wieder nach natürlichen Zahlen fragt, und
dann ausgibt, ob die eingegebene Zahl eine Quadratzahl ist.

#+begin_src
 Geben Sie eine Zahl ein: 3
 > keine Quadratzahl

 Geben Sie eine Zahl ein: 4
 > Quadratzahl

 Geben Sie eine Zahl ein: 22
 > keine Quadratzahl

 Geben Sie eine Zahl ein: 100
 > Quadratzahl

 ...
#+end_src

** Priemzahlen
Schreibe ein Programmm, das den Benutzer immer wieder und wieder nach natürlichen Zahlen fragt, und
dann ausgibt, ob die eingegebene Zahl eine Priemzahl ist.

#+begin_src
 Geben Sie eine Zahl ein: 3
 > Priemzahl

 Geben Sie eine Zahl ein: 4
 > keine Priemzahl

 Geben Sie eine Zahl ein: 22
 > keine Priemzahl

 Geben Sie eine Zahl ein: 101
 > Priemzahl

 ...
#+end_src
* Hausaufgaben Tag 2
** Wörter zählen mit Dictionaries
Schreibe ein Programm, das den Benutzer nach einem Text fragt und dann ausgibt wie oft jedes Wort
in dem Text vorgekommen ist.

#+begin_src
 Geben Sie einen Text ein: Ein Text mit vielen vielen Wörter und mit vielen Zeichen

 Ein: 1
 Text: 1
 mit: 2
 vielen: 3
 Wörter: 1
 und: 1
 Zeichen: 1
#+end_src

Tips:
 - Man kann über die keys in dictionaries mit =for word in dict:= iterieren

** Fakultät
Schreibe ein Programm, das die Falkultät einer Zahl berechnet. Fakultät schreibt man so: $3!$. Das
ist "3 Fakultät". Zum Beispiel "5 Fakultät" sieht so aus $5!$. Und wie berechnet man das?

$$3! = 3 \cdot 2 \cdot 1 = 6$$

und

$$5! = 5 \cdot 4 \cdot 3 \cdot 2 \cdot 1 = 120$$

usw.

Das Programm soll dann so laufen:

#+begin_src
 Geben Sie eine Zahl ein: 3
 3! = 6
#+end_src

oder

#+begin_src
 Geben Sie eine Zahl ein: 5
 5! = 120
#+end_src

** Fibonacci Zahlen
Schreibe ein Programm das die n-te Fibonacci Zahl berechnet. Was sind die Fibonacci Zahlen?
Die Fibonacci Zahlen sind diese Zahlen:

$$1\ \ 1\ \ 2\ \ 3\ \ 5\ \ 8\ \ 13\ \ 21\ \ 34 \cdots usw$$

Die ersten beiden Zahlen sind $1$, danach ist jede Zahl die Summe aus den beiden Zahlen davor.
(Zum Beispiel $3 + 5 = 8$ oder $13 + 21 = 34$).

Ein Ablauf des Programms sieht dann so aus:

#+begin_src
 Geben Sie eine Zahl ein: 3
 fib(3) = 2
#+end_src

oder

#+begin_src
 Geben Sie eine Zahl ein: 5
 fib(5) = 5
#+end_src

oder

#+begin_src
 Geben Sie eine Zahl ein: 8
 fib(5) = 21
#+end_src
